import { RbacRole, RbacPermission, RbacUser, SodDiagnosticRule } from './types';

export const INITIAL_ROLES: RbacRole[] = [
  {
    id: 1,
    code: 'SUPER_ADMIN',
    name: 'Tổng Quản Trị Hệ Thống Tối Cao',
    description: 'Quyền tối cao kiểm soát toàn bộ 42 phân hệ ERP, cấu hình IAM hạt nhân, ký duyệt khóa mật mã & can thiệp khẩn cấp.',
    tier: 'TIER_1_SOVEREIGN',
    isSystem: true,
    userCount: 2,
    permissionsCount: 48,
    permissions: ['ALL_PERMISSIONS', 'IAM_MASTER_OVERRIDE', 'ENCRYPTION_KEY_ROTATION', 'GLOBAL_CONFIG_WRITE'],
    allowedBranches: ['ALL'],
    status: 'ACTIVE',
    updatedAt: '2026-09-10 18:30:00',
    auditChecksum: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
  },
  {
    id: 2,
    code: 'CFO_DIRECTOR',
    name: 'Giám Đốc Tài Chính & Kế Toán Trưởng',
    description: 'Quyền phê duyệt sổ cái kép GL, định mức thanh toán ngân hàng, báo cáo tài chính hợp nhất M21-M25.',
    tier: 'TIER_2_GOVERNANCE',
    isSystem: true,
    userCount: 3,
    permissionsCount: 28,
    permissions: ['FIN_APPROVE_UNLIMITED', 'GL_POST_AUTHORITY', 'TAX_INVOICE_SIGN', 'BUDGET_REALLOCATION'],
    allowedBranches: ['ALL'],
    status: 'ACTIVE',
    updatedAt: '2026-09-08 14:15:22',
    auditChecksum: '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8',
  },
  {
    id: 3,
    code: 'WH_REGIONAL_DIRECTOR',
    name: 'Giám Đốc Kho Vận & Chuỗi Cung Ứng Vùng',
    description: 'Quản trị điều chuyển hàng hóa liên chi nhánh, phê duyệt kiểm kê kho 3 trạng thái M08-M11, M18-M21.',
    tier: 'TIER_2_GOVERNANCE',
    isSystem: true,
    userCount: 4,
    permissionsCount: 22,
    permissions: ['INVENTORY_WRITE', 'STOCKTAKE_APPROVE', 'TRANSFER_INTER_BRANCH', 'SCRAP_DISPOSAL_SIGN'],
    allowedBranches: ['BR_HO', 'BR_HCM', 'BR_DN'],
    status: 'ACTIVE',
    updatedAt: '2026-09-07 09:40:11',
    auditChecksum: '4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a',
  },
  {
    id: 4,
    code: 'PROD_OPERATION_LEAD',
    name: 'Trưởng Phòng Điều Hành & Kế Hoạch Sản Xuất',
    description: 'Lập lệnh sản xuất MO, quản lý định mức BOM nguyên vật liệu, điều độ phân xưởng M12-M17.',
    tier: 'TIER_3_OPERATIONAL',
    isSystem: false,
    userCount: 3,
    permissionsCount: 18,
    permissions: ['MFG_ORDER_RELEASE', 'BOM_VERSION_APPROVE', 'CAPACITY_DISPATCH', 'ROUTING_MAINTENANCE'],
    allowedBranches: ['BR_HO', 'BR_HCM'],
    status: 'ACTIVE',
    updatedAt: '2026-09-05 11:20:00',
    auditChecksum: 'ef2d127de37b942baad06145e54b0c619a1f22327b2ebbcfbec78f5564afe39d',
  },
  {
    id: 5,
    code: 'QA_COMPLIANCE_OFFICER',
    name: 'Chuyên Viên Kiểm Soát Chất Lượng & ISO',
    description: 'Thanh tra mẫu kiểm nghiệm QC, ghi nhận vi phạm tiêu chuẩn kỹ thuật, ký chứng chỉ COA M16.',
    tier: 'TIER_3_OPERATIONAL',
    isSystem: false,
    userCount: 2,
    permissionsCount: 14,
    permissions: ['QC_INSPECT_APPROVE', 'NON_CONFORMANCE_FLAG', 'BATCH_HOLD_RELEASE', 'COA_SIGNATURE'],
    allowedBranches: ['ALL'],
    status: 'ACTIVE',
    updatedAt: '2026-09-04 16:55:18',
    auditChecksum: '8f434346648f6b96df89dda901c5176b10e6d0ceec3e4d9c72e90e7cfb429112',
  },
  {
    id: 6,
    code: 'CHIEF_INTERNAL_AUDITOR',
    name: 'Trưởng Ban Kiểm Toán Nội Bộ & Tuân Thủ',
    description: 'Quyền đọc và rà soát độc lập toàn bộ nhật ký bất biến M02, đối chiếu vết kiểm toán SHA-256.',
    tier: 'TIER_2_GOVERNANCE',
    isSystem: true,
    userCount: 2,
    permissionsCount: 16,
    permissions: ['AUDIT_IMMUTABLE_READ', 'FORENSIC_EXPORT', 'SOD_VIOLATION_INSPECT', 'SYSTEM_LOG_MONITOR'],
    allowedBranches: ['ALL'],
    status: 'ACTIVE',
    updatedAt: '2026-09-03 10:05:44',
    auditChecksum: 'ecd71870d1963316a97e3ac3408c9835ad8cf0f3c1bc703527c30265534f75ae',
  },
  {
    id: 7,
    code: 'SALES_COMMERCE_OPERATOR',
    name: 'Chuyên Viên Kinh Doanh & Phân Phối Bán Lẻ',
    description: 'Tiếp nhận đơn hàng SO, phát hành báo giá, tra cứu công nợ khách hàng và lịch trình giao hàng.',
    tier: 'TIER_3_OPERATIONAL',
    isSystem: false,
    userCount: 5,
    permissionsCount: 12,
    permissions: ['SALES_ORDER_CREATE', 'CUSTOMER_CRM_READ', 'PRICE_QUOTE_ISSUE', 'TRACKING_INSPECT'],
    allowedBranches: ['BR_HO', 'BR_HCM', 'BR_DN', 'BR_CT'],
    status: 'ACTIVE',
    updatedAt: '2026-09-01 08:30:15',
    auditChecksum: '252f10c83610ebca1a059c0bae8255eba2f95be4d1d7bcfa89d7248a82d9f111',
  },
];

export const INITIAL_PERMISSIONS: RbacPermission[] = [
  {
    id: 1,
    code: 'CORE_M03_GLOBAL_CONFIG',
    name: 'Cấu hình Tham số Toàn cục & Vận hành',
    category: 'CORE',
    moduleId: 'M03',
    endpoint: '/api/settings/parameters',
    riskLevel: 'CRITICAL',
    assignedRolesCount: 1,
    description: 'Thay đổi thông số doanh nghiệp, tiền tệ hối đoái, thiết lập sao lưu tự động và bảo trì hệ thống.',
    action: 'FULL',
  },
  {
    id: 2,
    code: 'CORE_M04_IAM_AUTHORITY',
    name: 'Quản trị Phân quyền Tối cao RBAC',
    category: 'CORE',
    moduleId: 'M04',
    endpoint: '/api/rbac/*',
    riskLevel: 'CRITICAL',
    assignedRolesCount: 1,
    description: 'Tạo, gán, sửa đổi vai trò hạt nhân và phân bổ quyền hạn cho tài khoản.',
    action: 'FULL',
  },
  {
    id: 3,
    code: 'AUDIT_M02_IMMUTABLE_LOG',
    name: 'Kiểm toán Nhật ký Bất biến & Đối chiếu Hash',
    category: 'GOVERNANCE',
    moduleId: 'M02',
    endpoint: '/api/audit/logs',
    riskLevel: 'HIGH',
    assignedRolesCount: 3,
    description: 'Truy vấn nhật ký kiểm toán không thể sửa đổi, đối chiếu hàm băm SHA-256 chuỗi khối.',
    action: 'READ',
  },
  {
    id: 4,
    code: 'FIN_M21_PAYMENT_APPROVE',
    name: 'Phê duyệt Lệnh Thanh toán & Ngân hàng',
    category: 'FINANCE',
    moduleId: 'M21',
    endpoint: '/api/finance/payment-orders/approve',
    riskLevel: 'CRITICAL',
    assignedRolesCount: 2,
    description: 'Duyệt chuyển tiền thanh toán cho nhà cung cấp, chi lương và nghĩa vụ thuế nhà nước.',
    action: 'APPROVE',
  },
  {
    id: 5,
    code: 'FIN_M23_GL_JOURNAL_POST',
    name: 'Ghi sổ Nhật ký Sổ cái Kép (GL Post)',
    category: 'FINANCE',
    moduleId: 'M23',
    endpoint: '/api/finance/general-ledger/post',
    riskLevel: 'CRITICAL',
    assignedRolesCount: 2,
    description: 'Ghi nhận bút toán Nợ/Có chính thức vào Sổ cái hệ thống, tạo cơ sở báo cáo tài chính.',
    action: 'WRITE',
  },
  {
    id: 6,
    code: 'INV_M08_STOCK_TRANSACTION',
    name: 'Thực hiện Giao dịch Xuất/Nhập/Chuyển Kho',
    category: 'SUPPLY_CHAIN',
    moduleId: 'M08',
    endpoint: '/api/inventory/transactions',
    riskLevel: 'HIGH',
    assignedRolesCount: 3,
    description: 'Ghi nhận biến động vật lý hàng hóa theo cơ chế single-writer của InventoryService.',
    action: 'WRITE',
  },
  {
    id: 7,
    code: 'INV_M19_STOCKTAKE_ADJUST',
    name: 'Kiểm kê Kho & Đề xuất Bút toán Điều chỉnh',
    category: 'SUPPLY_CHAIN',
    moduleId: 'M19',
    endpoint: '/api/inventory/stocktake/adjust',
    riskLevel: 'HIGH',
    assignedRolesCount: 2,
    description: 'Chốt số liệu kiểm đếm thực tế và lập phiếu điều chỉnh chênh lệch tồn kho.',
    action: 'APPROVE',
  },
  {
    id: 8,
    code: 'MFG_M14_PROD_ORDER_DISPATCH',
    name: 'Điều độ Lệnh Sản xuất & Bắn Lịch Phân xưởng',
    category: 'MANUFACTURING',
    moduleId: 'M14',
    endpoint: '/api/manufacturing/orders/dispatch',
    riskLevel: 'MEDIUM',
    assignedRolesCount: 2,
    description: 'Phát hành lệnh làm việc cho dây chuyền, phân bổ NVL và ca kíp nhân công.',
    action: 'WRITE',
  },
  {
    id: 9,
    code: 'SALES_M30_ORDER_FULFILL',
    name: 'Xử lý Khớp Đơn Hàng & Giữ Chỗ Tồn Kho (Lock)',
    category: 'SALES',
    moduleId: 'M30',
    endpoint: '/api/sales/orders/fulfill',
    riskLevel: 'STANDARD',
    assignedRolesCount: 3,
    description: 'Tiếp nhận đơn hàng khách hàng, kích hoạt khóa giữ chỗ hàng tồn kho khả dụng.',
    action: 'WRITE',
  },
  {
    id: 10,
    code: 'BI_M37_EXECUTIVE_DASHBOARD',
    name: 'Xem Báo cáo Tổng thể Doanh nghiệp BI',
    category: 'GOVERNANCE',
    moduleId: 'M37',
    endpoint: '/api/bi/executive-metrics',
    riskLevel: 'MEDIUM',
    assignedRolesCount: 4,
    description: 'Xem chỉ số P&L, dòng tiền, vòng quay hàng tồn kho và hiệu suất toàn tập đoàn.',
    action: 'READ',
  },
];

export const INITIAL_USERS: RbacUser[] = [
  {
    id: 101,
    username: 'superadmin_hq',
    fullName: 'Lê Đình Hoàng (SuperAdmin)',
    email: 'hoang.le@nexussync.vn',
    roleId: 1,
    roleCode: 'SUPER_ADMIN',
    roleName: 'Tổng Quản Trị Hệ Thống Tối Cao',
    branchScope: 'ALL',
    branchName: 'Toàn Quốc (Tất cả Chi nhánh)',
    status: 'ACTIVE',
    lastLogin: '2026-09-11 08:35:10',
    mfaEnabled: true,
    avatarBg: 'bg-purple-600',
  },
  {
    id: 102,
    username: 'cfo_nguyen',
    fullName: 'Nguyễn Thị Bích Ngọc (CFO)',
    email: 'ngoc.nguyen@nexussync.vn',
    roleId: 2,
    roleCode: 'CFO_DIRECTOR',
    roleName: 'Giám Đốc Tài Chính & Kế Toán Trưởng',
    branchScope: 'ALL',
    branchName: 'Toàn Quốc (Tất cả Chi nhánh)',
    status: 'ACTIVE',
    lastLogin: '2026-09-11 08:12:45',
    mfaEnabled: true,
    avatarBg: 'bg-blue-600',
  },
  {
    id: 103,
    username: 'wh_director_bac',
    fullName: 'Vũ Đức Minh (GĐ Kho Miền Bắc)',
    email: 'minh.vu@nexussync.vn',
    roleId: 3,
    roleCode: 'WH_REGIONAL_DIRECTOR',
    roleName: 'Giám Đốc Kho Vận & Chuỗi Cung Ứng Vùng',
    branchScope: 'BR_HO',
    branchName: 'Hà Nội HQ (BR_HO)',
    status: 'ACTIVE',
    lastLogin: '2026-09-11 07:55:00',
    mfaEnabled: true,
    avatarBg: 'bg-emerald-600',
  },
  {
    id: 104,
    username: 'wh_director_nam',
    fullName: 'Trần Hữu Thắng (GĐ Kho Miền Nam)',
    email: 'thang.tran@nexussync.vn',
    roleId: 3,
    roleCode: 'WH_REGIONAL_DIRECTOR',
    roleName: 'Giám Đốc Kho Vận & Chuỗi Cung Ứng Vùng',
    branchScope: 'BR_HCM',
    branchName: 'Hồ Chí Minh (BR_HCM)',
    status: 'ACTIVE',
    lastLogin: '2026-09-11 08:05:22',
    mfaEnabled: true,
    avatarBg: 'bg-emerald-600',
  },
  {
    id: 105,
    username: 'prod_lead_factory1',
    fullName: 'Phạm Hồng Sơn (Trưởng SX Nhà máy 1)',
    email: 'son.pham@nexussync.vn',
    roleId: 4,
    roleCode: 'PROD_OPERATION_LEAD',
    roleName: 'Trưởng Phòng Điều Hành & Kế Hoạch Sản Xuất',
    branchScope: 'BR_HO',
    branchName: 'Hà Nội HQ (BR_HO)',
    status: 'ACTIVE',
    lastLogin: '2026-09-10 17:30:19',
    mfaEnabled: false,
    avatarBg: 'bg-amber-600',
  },
  {
    id: 106,
    username: 'qa_officer_hang',
    fullName: 'Đỗ Thúy Hằng (Trưởng nhóm QC/ISO)',
    email: 'hang.do@nexussync.vn',
    roleId: 5,
    roleCode: 'QA_COMPLIANCE_OFFICER',
    roleName: 'Chuyên Viên Kiểm Soát Chất Lượng & ISO',
    branchScope: 'ALL',
    branchName: 'Toàn Quốc (Tất cả Chi nhánh)',
    status: 'ACTIVE',
    lastLogin: '2026-09-11 08:22:15',
    mfaEnabled: true,
    avatarBg: 'bg-indigo-600',
  },
  {
    id: 107,
    username: 'auditor_trung',
    fullName: 'Hoàng Văn Trung (Kiểm Toán Viên)',
    email: 'trung.hoang@nexussync.vn',
    roleId: 6,
    roleCode: 'CHIEF_INTERNAL_AUDITOR',
    roleName: 'Trưởng Ban Kiểm Toán Nội Bộ & Tuân Thủ',
    branchScope: 'ALL',
    branchName: 'Toàn Quốc (Tất cả Chi nhánh)',
    status: 'ACTIVE',
    lastLogin: '2026-09-11 06:45:00',
    mfaEnabled: true,
    avatarBg: 'bg-slate-700',
  },
  {
    id: 108,
    username: 'sales_rep_loan',
    fullName: 'Ngô Thanh Loan (Chuyên Viên Bán Hàng)',
    email: 'loan.ngo@nexussync.vn',
    roleId: 7,
    roleCode: 'SALES_COMMERCE_OPERATOR',
    roleName: 'Chuyên Viên Kinh Doanh & Phân Phối Bán Lẻ',
    branchScope: 'BR_HCM',
    branchName: 'Hồ Chí Minh (BR_HCM)',
    status: 'ACTIVE',
    lastLogin: '2026-09-11 08:30:40',
    mfaEnabled: false,
    avatarBg: 'bg-teal-600',
  },
];

export const INITIAL_SOD_RULES: SodDiagnosticRule[] = [
  {
    id: 'SOD_01_MAKER_CHECKER_FIN',
    code: 'SOD-FIN-01',
    name: 'Phân Tách Lập Phiếu Chi & Phê Duyệt Thanh Toán',
    category: 'FINANCE_GOVERNANCE',
    riskSeverity: 'CRITICAL',
    description: 'Ngăn chặn một tài khoản kiêm nhiệm cả quyền lập đề nghị chi tiền và thẩm quyền phê duyệt lệnh chi ngân hàng.',
    conflictingPermissions: ['FIN_M21_PAYMENT_CREATE', 'FIN_M21_PAYMENT_APPROVE'],
    status: 'PASSED',
    violationCount: 0,
    details: 'Đã quét 16 tài khoản. Không phát hiện tài khoản nào có cả 2 đặc quyền lập và duyệt thanh toán.',
    lastAudited: '2026-09-11 08:35:00',
    remediationGuide: 'Nếu phát hiện vi phạm, hệ thống tự động thu hồi quyền phê duyệt và chuyển về trạng thái Maker độc lập.',
  },
  {
    id: 'SOD_02_PROCURE_RECEIPT',
    code: 'SOD-SCM-02',
    name: 'Phân Tách Đặt Mua Hàng & Nghiệm Thu Nhập Kho',
    category: 'SUPPLY_CHAIN',
    riskSeverity: 'HIGH',
    description: 'Nhân viên phát hành đơn mua hàng (PO) không được phép tự tay ký xác nhận nhập kho thực tế (GRN).',
    conflictingPermissions: ['PURCHASE_M12_PO_CREATE', 'INV_M08_GRN_RECEIVE'],
    status: 'PASSED',
    violationCount: 0,
    details: 'Kiểm tra khớp 100%. Phân định rõ ràng giữa phòng Mua Hàng và Thủ kho phụ trách tiếp nhận.',
    lastAudited: '2026-09-11 08:30:15',
    remediationGuide: 'Tách biệt vai trò Buyer và Warehouse Receiver tại cấp độ chi nhánh.',
  },
  {
    id: 'SOD_03_STOCKTAKE_ADJUST',
    code: 'SOD-INV-03',
    name: 'Phân Tách Kiểm Đếm Tồn Kho & Duyệt Điều Chỉnh Số Dư',
    category: 'INVENTORY_CONTROL',
    riskSeverity: 'CRITICAL',
    description: 'Nhân viên thực hiện kiểm kê thực tế không được quyền tự duyệt bút toán điều chỉnh hao hụt hay sai lệch.',
    conflictingPermissions: ['INV_M19_COUNT_SUBMIT', 'INV_M20_ADJUSTMENT_SIGN'],
    status: 'PASSED',
    violationCount: 0,
    details: 'Mọi bút toán điều chỉnh chênh lệch kiểm kê bắt buộc phải có chữ ký số của Kế toán trưởng hoặc Giám đốc Kho.',
    lastAudited: '2026-09-11 08:25:00',
    remediationGuide: 'Áp dụng quy trình duyệt 2 cấp (Two-man rule) trước khi cập nhật số dư kho.',
  },
  {
    id: 'SOD_04_CASHIER_GL',
    code: 'SOD-ACC-04',
    name: 'Phân Tách Quản Lý Tiền Mặt & Sửa Sổ Cái Tổng Hợp',
    category: 'FINANCE_GOVERNANCE',
    riskSeverity: 'CRITICAL',
    description: 'Thủ quỹ nắm giữ tiền mặt tại quỹ tuyệt đối không được phép chỉnh sửa tài khoản Sổ Cái (GL) 111/112.',
    conflictingPermissions: ['CASH_M22_VAULT_MANAGE', 'FIN_M23_GL_JOURNAL_POST'],
    status: 'PASSED',
    violationCount: 0,
    details: 'Bảo đảm tính độc lập giữa tài sản hữu hình và hồ sơ sổ sách kế toán kép.',
    lastAudited: '2026-09-11 08:20:00',
    remediationGuide: 'Khóa quyền GL đối với tất cả vai trò thuộc bộ phận quỹ.',
  },
  {
    id: 'SOD_05_TOKEN_SECURITY',
    code: 'SEC-IAM-05',
    name: 'Tính Toàn Vẹn Chữ Ký Token & Chống Leo Thang Đặc Quyền',
    category: 'IAM_SECURITY',
    riskSeverity: 'CRITICAL',
    description: 'Kiểm tra tính hợp lệ của chữ ký HMAC-SHA256 trong phiên JWT, phát hiện nỗ lực giả mạo Payload Claims.',
    conflictingPermissions: ['TOKEN_SIGNATURE_TAMPER', 'PRIVILEGE_ESCALATE'],
    status: 'PASSED',
    violationCount: 0,
    details: '100% token phiên đều có khóa ký điện tử cấp từ HSM Module bảo mật phần cứng.',
    lastAudited: '2026-09-11 08:35:10',
    remediationGuide: 'Tự động revoke session ngay lập tức khi phát hiện token không khớp checksum HMAC.',
  },
];
