import { RbacRole, RbacPermission, RbacUser, SodDiagnosticRule } from './types';

export const INITIAL_ROLES: RbacRole[] = [
  {
    id: 1,
    code: 'SUPER_ADMIN',
    name: 'Tổng Quản Trị Hệ Thống Tối Cao',
    description: 'Quyền tối cao kiểm soát toàn bộ 42 phân hệ ERP, cấu hình IAM hạt nhân, ký duyệt khóa mật mã & can thiệp khẩn cấp.',
    tier: 'TIER_1_SOVEREIGN',
    isSystem: true,
    userCount: 2,
    permissionsCount: 48,
    permissions: ['ALL_PERMISSIONS', 'IAM_MASTER_OVERRIDE', 'ENCRYPTION_KEY_ROTATION', 'GLOBAL_CONFIG_WRITE'],
    allowedBranches: ['ALL'],
    status: 'ACTIVE',
    updatedAt: '2026-09-10 18:30:00',
    auditChecksum: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
  },
  {
    id: 2,
    code: 'CFO_DIRECTOR',
    name: 'Giám Đốc Tài Chính & Kế Toán Trưởng',
    description: 'Quyền phê duyệt sổ cái kép GL, định mức thanh toán ngân hàng, báo cáo tài chính hợp nhất M21-M25.',
    tier: 'TIER_2_GOVERNANCE',
    isSystem: true,
    userCount: 3,
    permissionsCount: 28,
    permissions: ['FIN_APPROVE_UNLIMITED', 'GL_POST_AUTHORITY', 'TAX_INVOICE_SIGN', 'BUDGET_REALLOCATION'],
    allowedBranches: ['ALL'],
    status: 'ACTIVE',
    updatedAt: '2026-09-08 14:15:22',
    auditChecksum: '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8',
  },
  {
    id: 3,
    code: 'WH_REGIONAL_DIRECTOR',
    name: 'Giám Đốc Kho Vận & Chuỗi Cung Ứng Vùng',
    description: 'Quản trị điều chuyển hàng hóa liên chi nhánh, phê duyệt kiểm kê kho 3 trạng thái M08-M11, M18-M21.',
    tier: 'TIER_2_GOVERNANCE',
    isSystem: true,
    userCount: 4,
    permissionsCount: 22,
    permissions: ['INVENTORY_WRITE', 'STOCKTAKE_APPROVE', 'TRANSFER_INTER_BRANCH', 'SCRAP_DISPOSAL_SIGN'],
    allowedBranches: ['BR_HO', 'BR_HCM', 'BR_DN'],
    status: 'ACTIVE',
    updatedAt: '2026-09-07 09:40:11',
    auditChecksum: '4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a',
  },
  {
    id: 4,
    code: 'PROD_OPERATION_LEAD',
    name: 'Trưởng Phòng Điều Hành & Kế Hoạch Sản Xuất',
    description: 'Lập lệnh sản xuất MO, quản lý định mức BOM nguyên vật liệu, điều độ phân xưởng M12-M17.',
    tier: 'TIER_3_OPERATIONAL',
    isSystem: false,
    userCount: 3,
    permissionsCount: 18,
    permissions: ['MFG_ORDER_RELEASE', 'BOM_VERSION_APPROVE', 'CAPACITY_DISPATCH', 'ROUTING_MAINTENANCE'],
    allowedBranches: ['BR_HO', 'BR_HCM'],
    status: 'ACTIVE',
    updatedAt: '2026-09-05 11:20:00',
    auditChecksum: 'ef2d127de37b942baad06145e54b0c619a1f22327b2ebbcfbec78f5564afe39d',
  },
  {
    id: 5,
    code: 'QA_COMPLIANCE_OFFICER',
    name: 'Chuyên Viên Kiểm Soát Chất Lượng & ISO',
    description: 'Thanh tra mẫu kiểm nghiệm QC, ghi nhận vi phạm tiêu chuẩn kỹ thuật, ký chứng chỉ COA M16.',
    tier: 'TIER_3_OPERATIONAL',
    isSystem: false,
    userCount: 2,
    permissionsCount: 14,
    permissions: ['QC_INSPECT_APPROVE', 'NON_CONFORMANCE_FLAG', 'BATCH_HOLD_RELEASE', 'COA_SIGNATURE'],
    allowedBranches: ['ALL'],
    status: 'ACTIVE',
    updatedAt: '2026-09-04 16:55:18',
    auditChecksum: '8f434346648f6b96df89dda901c5176b10e6d0ceec3e4d9c72e90e7cfb429112',
  },
  {
    id: 6,
    code: 'CHIEF_INTERNAL_AUDITOR',
    name: 'Trưởng Ban Kiểm Toán Nội Bộ & Tuân Thủ',
    description: 'Quyền đọc và rà soát độc lập toàn bộ nhật ký bất biến M02, đối chiếu vết kiểm toán SHA-256.',
    tier: 'TIER_2_GOVERNANCE',
    isSystem: true,
    userCount: 2,
    permissionsCount: 16,
    permissions: ['AUDIT_IMMUTABLE_READ', 'FORENSIC_EXPORT', 'SOD_VIOLATION_INSPECT', 'SYSTEM_LOG_MONITOR'],
    allowedBranches: ['ALL'],
    status: 'ACTIVE',
    updatedAt: '2026-09-03 10:05:44',
    auditChecksum: 'ecd71870d1963316a97e3ac3408c9835ad8cf0f3c1bc703527c30265534f75ae',
  },
  {
    id: 7,
    code: 'SALES_COMMERCE_OPERATOR',
    name: 'Chuyên Viên Kinh Doanh & Phân Phối Bán Lẻ',
    description: 'Tiếp nhận đơn hàng SO, phát hành báo giá, tra cứu công nợ khách hàng và lịch trình giao hàng.',
    tier: 'TIER_3_OPERATIONAL',
    isSystem: false,
    userCount: 5,
    permissionsCount: 12,
    permissions: ['SALES_ORDER_CREATE', 'CUSTOMER_CRM_READ', 'PRICE_QUOTE_ISSUE', 'TRACKING_INSPECT'],
    allowedBranches: ['BR_HO', 'BR_HCM', 'BR_DN', 'BR_CT'],
    status: 'ACTIVE',
    updatedAt: '2026-09-01 08:30:15',
    auditChecksum: '252f10c83610ebca1a059c0bae8255eba2f95be4d1d7bcfa89d7248a82d9f111',
  },
];

export const INITIAL_PERMISSIONS: RbacPermission[] = [
  {
    id: 1,
    code: 'CORE_M03_GLOBAL_CONFIG',
    name: 'Cấu hình Tham số Toàn cục & Vận hành',
    category: 'CORE',
    moduleId: 'M03',
    endpoint: '/api/settings/parameters',
    riskLevel: 'CRITICAL',
    assignedRolesCount: 1,
    description: 'Thay đổi thông số doanh nghiệp, tiền tệ hối đoái, thiết lập sao lưu tự động và bảo trì hệ thống.',
    action: 'FULL',
  },
  {
    id: 2,
    code: 'CORE_M04_IAM_AUTHORITY',
    name: 'Quản trị Phân quyền Tối cao RBAC',
    category: 'CORE',
    moduleId: 'M04',
    endpoint: '/api/rbac/*',
    riskLevel: 'CRITICAL',
    assignedRolesCount: 1,
    description: 'Tạo, gán, sửa đổi vai trò hạt nhân và phân bổ quyền hạn cho tài khoản.',
    action: 'FULL',
  },
  {
    id: 3,
    code: 'AUDIT_M02_IMMUTABLE_LOG',
    name: 'Kiểm toán Nhật ký Bất biến & Đối chiếu Hash',
    category: 'GOVERNANCE',
    moduleId: 'M02',
    endpoint: '/api/audit/logs',
    riskLevel: 'HIGH',
    assignedRolesCount: 3,
    description: 'Truy vấn nhật ký kiểm toán không thể sửa đổi, đối chiếu hàm băm SHA-256 chuỗi khối.',
    action: 'READ',
  },
  {
    id: 4,
    code: 'FIN_M21_PAYMENT_APPROVE',
    name: 'Phê duyệt Lệnh Thanh toán & Ngân hàng',
    category: 'FINANCE',
    moduleId: 'M21',
    endpoint: '/api/finance/payment-orders/approve',
    riskLevel: 'CRITICAL',
    assignedRolesCount: 2,
    description: 'Duyệt chuyển tiền thanh toán cho nhà cung cấp, chi lương và nghĩa vụ thuế nhà nước.',
    action: 'APPROVE',
  },
  {
    id: 5,
    code: 'FIN_M23_GL_JOURNAL_POST',
    name: 'Ghi sổ Nhật ký Sổ cái Kép (GL Post)',
    category: 'FINANCE',
    moduleId: 'M23',
    endpoint: '/api/finance/general-ledger/post',
    riskLevel: 'CRITICAL',
    assignedRolesCount: 2,
    description: 'Ghi nhận bút toán Nợ/Có chính thức vào Sổ cái hệ thống, tạo cơ sở báo cáo tài chính.',
    action: 'WRITE',
  },
  {
    id: 6,
    code: 'INV_M08_STOCK_TRANSACTION',
    name: 'Thực hiện Giao dịch Xuất/Nhập/Chuyển Kho',
    category: 'SUPPLY_CHAIN',
    moduleId: 'M08',
    endpoint: '/api/inventory/transactions',
    riskLevel: 'HIGH',
    assignedRolesCount: 3,
    description: 'Ghi nhận biến động vật lý hàng hóa theo cơ chế single-writer của InventoryService.',
    action: 'WRITE',
  },
  {
    id: 7,
    code: 'INV_M19_STOCKTAKE_ADJUST',
    name: 'Kiểm kê Kho & Đề xuất Bút toán Điều chỉnh',
    category: 'SUPPLY_CHAIN',
    moduleId: 'M19',
    endpoint: '/api/inventory/stocktake/adjust',
    riskLevel: 'HIGH',
    assignedRolesCount: 2,
    description: 'Chốt số liệu kiểm đếm thực tế và lập phiếu điều chỉnh chênh lệch tồn kho.',
    action: 'APPROVE',
  },
  {
    id: 8,
    code: 'MFG_M14_PROD_ORDER_DISPATCH',
    name: 'Điều độ Lệnh Sản xuất & Bắn Lịch Phân xưởng',
    category: 'MANUFACTURING',
    moduleId: 'M14',
    endpoint: '/api/manufacturing/orders/dispatch',
    riskLevel: 'MEDIUM',
    assignedRolesCount: 2,
    description: 'Phát hành lệnh làm việc cho dây chuyền, phân bổ NVL và ca kíp nhân công.',
    action: 'WRITE',
  },
  {
    id: 9,
    code: 'SALES_M30_ORDER_FULFILL',
    name: 'Xử lý Khớp Đơn Hàng & Giữ Chỗ Tồn Kho (Lock)',
    category: 'SALES',
    moduleId: 'M30',
    endpoint: '/api/sales/orders/fulfill',
    riskLevel: 'STANDARD',
    assignedRolesCount: 3,
    description: 'Tiếp nhận đơn hàng khách hàng, kích hoạt khóa giữ chỗ hàng tồn kho khả dụng.',
    action: 'WRITE',
  },
  {
    id: 10,
    code: 'BI_M37_EXECUTIVE_DASHBOARD',
    name: 'Xem Báo cáo Tổng thể Doanh nghiệp BI',
    category: 'GOVERNANCE',
    moduleId: 'M37',
    endpoint: '/api/bi/executive-metrics',
    riskLevel: 'MEDIUM',
    assignedRolesCount: 4,
    description: 'Xem chỉ số P&L, dòng tiền, vòng quay hàng tồn kho và hiệu suất toàn tập đoàn.',
    action: 'READ',
  },
];

export const INITIAL_USERS: RbacUser[] = [
  {
    id: 101,
    username: 'superadmin_hq',
    fullName: 'Lê Đình Hoàng (SuperAdmin)',
    email: 'hoang.le@nexussync.vn',
    roleId: 1,
    roleCode: 'SUPER_ADMIN',
    roleName: 'Tổng Quản Trị Hệ Thống Tối Cao',
    branchScope: 'ALL',
    branchName: 'Toàn Quốc (Tất cả Chi nhánh)',
    status: 'ACTIVE',
    lastLogin: '2026-09-11 08:35:10',
    mfaEnabled: true,
    avatarBg: 'bg-purple-600',
  },
  {
    id: 102,
    username: 'cfo_nguyen',
    fullName: 'Nguyễn Thị Bích Ngọc (CFO)',
    email: 'ngoc.nguyen@nexussync.vn',
    roleId: 2,
    roleCode: 'CFO_DIRECTOR',
    roleName: 'Giám Đốc Tài Chính & Kế Toán Trưởng',
    branchScope: 'ALL',
    branchName: 'Toàn Quốc (Tất cả Chi nhánh)',
    status: 'ACTIVE',
    lastLogin: '2026-09-11 08:12:45',
    mfaEnabled: true,
    avatarBg: 'bg-blue-600',
  },
  {
    id: 103,
    username: 'wh_director_bac',
    fullName: 'Vũ Đức Minh (GĐ Kho Miền Bắc)',
    email: 'minh.vu@nexussync.vn',
    roleId: 3,
    roleCode: 'WH_REGIONAL_DIRECTOR',
    roleName: 'Giám Đốc Kho Vận & Chuỗi Cung Ứng Vùng',
    branchScope: 'BR_HO',
    branchName: 'Hà Nội HQ (BR_HO)',
    status: 'ACTIVE',
    lastLogin: '2026-09-11 07:55:00',
    mfaEnabled: true,
    avatarBg: 'bg-emerald-600',
  },
  {
    id: 104,
    username: 'wh_director_nam',
    fullName: 'Trần Hữu Thắng (GĐ Kho Miền Nam)',
    email: 'thang.tran@nexussync.vn',
    roleId: 3,
    roleCode: 'WH_REGIONAL_DIRECTOR',
    roleName: 'Giám Đốc Kho Vận & Chuỗi Cung Ứng Vùng',
    branchScope: 'BR_HCM',
    branchName: 'Hồ Chí Minh (BR_HCM)',
    status: 'ACTIVE',
    lastLogin: '2026-09-11 08:05:22',
    mfaEnabled: true,
    avatarBg: 'bg-emerald-600',
  },
  {
    id: 105,
    username: 'prod_lead_factory1',
    fullName: 'Phạm Hồng Sơn (Trưởng SX Nhà máy 1)',
    email: 'son.pham@nexussync.vn',
    roleId: 4,
    roleCode: 'PROD_OPERATION_LEAD',
    roleName: 'Trưởng Phòng Điều Hành & Kế Hoạch Sản Xuất',
    branchScope: 'BR_HO',
    branchName: 'Hà Nội HQ (BR_HO)',
    status: 'ACTIVE',
    lastLogin: '2026-09-10 17:30:19',
    mfaEnabled: false,
    avatarBg: 'bg-amber-600',
  },
  {
    id: 106,
    username: 'qa_officer_hang',
    fullName: 'Đỗ Thúy Hằng (Trưởng nhóm QC/ISO)',
    email: 'hang.do@nexussync.vn',
    roleId: 5,
    roleCode: 'QA_COMPLIANCE_OFFICER',
    roleName: 'Chuyên Viên Kiểm Soát Chất Lượng & ISO',
    branchScope: 'ALL',
    branchName: 'Toàn Quốc (Tất cả Chi nhánh)',
    status: 'ACTIVE',
    lastLogin: '2026-09-11 08:22:15',
    mfaEnabled: true,
    avatarBg: 'bg-indigo-600',
  },
  {
    id: 107,
    username: 'auditor_trung',
    fullName: 'Hoàng Văn Trung (Kiểm Toán Viên)',
    email: 'trung.hoang@nexussync.vn',
    roleId: 6,
    roleCode: 'CHIEF_INTERNAL_AUDITOR',
    roleName: 'Trưởng Ban Kiểm Toán Nội Bộ & Tuân Thủ',
    branchScope: 'ALL',
    branchName: 'Toàn Quốc (Tất cả Chi nhánh)',
    status: 'ACTIVE',
    lastLogin: '2026-09-11 06:45:00',
    mfaEnabled: true,
    avatarBg: 'bg-slate-700',
  },
  {
    id: 108,
    username: 'sales_rep_loan',
    fullName: 'Ngô Thanh Loan (Chuyên Viên Bán Hàng)',
    email: 'loan.ngo@nexussync.vn',
    roleId: 7,
    roleCode: 'SALES_COMMERCE_OPERATOR',
    roleName: 'Chuyên Viên Kinh Doanh & Phân Phối Bán Lẻ',
    branchScope: 'BR_HCM',
    branchName: 'Hồ Chí Minh (BR_HCM)',
    status: 'ACTIVE',
    lastLogin: '2026-09-11 08:30:40',
    mfaEnabled: false,
    avatarBg: 'bg-teal-600',
  },
];

export const INITIAL_SOD_RULES: SodDiagnosticRule[] = [
  {
    id: 'SOD_01_MAKER_CHECKER_FIN',
    code: 'SOD-FIN-01',
    name: 'Phân Tách Lập Phiếu Chi & Phê Duyệt Thanh Toán',
    category: 'FINANCE_GOVERNANCE',
    riskSeverity: 'CRITICAL',
    description: 'Ngăn chặn một tài khoản kiêm nhiệm cả quyền lập đề nghị chi tiền và thẩm quyền phê duyệt lệnh chi ngân hàng.',
    conflictingPermissions: ['FIN_M21_PAYMENT_CREATE', 'FIN_M21_PAYMENT_APPROVE'],
    status: 'PASSED',
    violationCount: 0,
    details: 'Đã quét 16 tài khoản. Không phát hiện tài khoản nào có cả 2 đặc quyền lập và duyệt thanh toán.',
    lastAudited: '2026-09-11 08:35:00',
    remediationGuide: 'Nếu phát hiện vi phạm, hệ thống tự động thu hồi quyền phê duyệt và chuyển về trạng thái Maker độc lập.',
  },
  {
    id: 'SOD_02_PROCURE_RECEIPT',
    code: 'SOD-SCM-02',
    name: 'Phân Tách Đặt Mua Hàng & Nghiệm Thu Nhập Kho',
    category: 'SUPPLY_CHAIN',
    riskSeverity: 'HIGH',
    description: 'Nhân viên phát hành đơn mua hàng (PO) không được phép tự tay ký xác nhận nhập kho thực tế (GRN).',
    conflictingPermissions: ['PURCHASE_M12_PO_CREATE', 'INV_M08_GRN_RECEIVE'],
    status: 'PASSED',
    violationCount: 0,
    details: 'Kiểm tra khớp 100%. Phân định rõ ràng giữa phòng Mua Hàng và Thủ kho phụ trách tiếp nhận.',
    lastAudited: '2026-09-11 08:30:15',
    remediationGuide: 'Tách biệt vai trò Buyer và Warehouse Receiver tại cấp độ chi nhánh.',
  },
  {
    id: 'SOD_03_STOCKTAKE_ADJUST',
    code: 'SOD-INV-03',
    name: 'Phân Tách Kiểm Đếm Tồn Kho & Duyệt Điều Chỉnh Số Dư',
    category: 'INVENTORY_CONTROL',
    riskSeverity: 'CRITICAL',
    description: 'Nhân viên thực hiện kiểm kê thực tế không được quyền tự duyệt bút toán điều chỉnh hao hụt hay sai lệch.',
    conflictingPermissions: ['INV_M19_COUNT_SUBMIT', 'INV_M20_ADJUSTMENT_SIGN'],
    status: 'PASSED',
    violationCount: 0,
    details: 'Mọi bút toán điều chỉnh chênh lệch kiểm kê bắt buộc phải có chữ ký số của Kế toán trưởng hoặc Giám đốc Kho.',
    lastAudited: '2026-09-11 08:25:00',
    remediationGuide: 'Áp dụng quy trình duyệt 2 cấp (Two-man rule) trước khi cập nhật số dư kho.',
  },
  {
    id: 'SOD_04_CASHIER_GL',
    code: 'SOD-ACC-04',
    name: 'Phân Tách Quản Lý Tiền Mặt & Sửa Sổ Cái Tổng Hợp',
    category: 'FINANCE_GOVERNANCE',
    riskSeverity: 'CRITICAL',
    description: 'Thủ quỹ nắm giữ tiền mặt tại quỹ tuyệt đối không được phép chỉnh sửa tài khoản Sổ Cái (GL) 111/112.',
    conflictingPermissions: ['CASH_M22_VAULT_MANAGE', 'FIN_M23_GL_JOURNAL_POST'],
    status: 'PASSED',
    violationCount: 0,
    details: 'Bảo đảm tính độc lập giữa tài sản hữu hình và hồ sơ sổ sách kế toán kép.',
    lastAudited: '2026-09-11 08:20:00',
    remediationGuide: 'Khóa quyền GL đối với tất cả vai trò thuộc bộ phận quỹ.',
  },
  {
    id: 'SOD_05_TOKEN_SECURITY',
    code: 'SEC-IAM-05',
    name: 'Tính Toàn Vẹn Chữ Ký Token & Chống Leo Thang Đặc Quyền',
    category: 'IAM_SECURITY',
    riskSeverity: 'CRITICAL',
    description: 'Kiểm tra tính hợp lệ của chữ ký HMAC-SHA256 trong phiên JWT, phát hiện nỗ lực giả mạo Payload Claims.',
    conflictingPermissions: ['TOKEN_SIGNATURE_TAMPER', 'PRIVILEGE_ESCALATE'],
    status: 'PASSED',
    violationCount: 0,
    details: '100% token phiên đều có khóa ký điện tử cấp từ HSM Module bảo mật phần cứng.',
    lastAudited: '2026-09-11 08:35:10',
    remediationGuide: 'Tự động revoke session ngay lập tức khi phát hiện token không khớp checksum HMAC.',
  },
  {
    id: 'SOD_06_SUPERADMIN_4EYES',
    code: 'SOD-IAM-06',
    name: 'Nguyên Tắc 4 Mắt (4-Eyes Principle) Cấp Quyền SuperAdmin',
    category: 'IAM_SECURITY',
    riskSeverity: 'CRITICAL',
    description: 'Người tạo Role hoặc Admin không được tự thăng cấp tài khoản của mình thành SuperAdmin mà không có xác nhận độc lập của người thứ 2.',
    conflictingPermissions: ['SELF_PROMOTION_SUPERADMIN', 'BYPASS_4EYES_APPROVAL'],
    status: 'PASSED',
    violationCount: 0,
    details: 'Chính sách Dual-Approval đang hoạt động. Cần xác nhận bảo mật cấp 2 trước khi kích hoạt Tier-1 Sovereign.',
    lastAudited: '2026-09-15 08:00:00',
    remediationGuide: 'Bắt buộc dùng tính năng Phê duyệt kép (Two-man rule) khi gán vai trò SUPER_ADMIN.',
  },
  {
    id: 'SOD_07_DISCOUNT_APPROVE',
    code: 'SOD-SALES-07',
    name: 'Phân Tách Nhân Viên Bán Hàng & Duyệt Chiết Khấu Quá Hạn',
    category: 'SALES_GOVERNANCE',
    riskSeverity: 'HIGH',
    description: 'Chuyên viên kinh doanh trực tiếp tạo đơn hàng SO không được tự duyệt mức chiết khấu vượt ngưỡng 15%.',
    conflictingPermissions: ['SALES_ORDER_CREATE', 'DISCOUNT_THRESHOLD_OVERRIDE'],
    status: 'PASSED',
    violationCount: 0,
    details: 'Mọi đơn hàng vượt ngưỡng chiết khấu tự động chuyển tiếp lên Giám đốc Kinh doanh phê duyệt.',
    lastAudited: '2026-09-15 08:10:00',
    remediationGuide: 'Định tuyến phê duyệt đơn hàng có chiết khấu cao sang cấp quản lý.',
  },
  {
    id: 'SOD_08_BANK_SIGNER',
    code: 'SOD-TREASURY-08',
    name: 'Phân Tách Lập Lệnh Chuyển Tiền & Duyệt Lệnh Thanh Toán Ngân Hàng',
    category: 'FINANCE_GOVERNANCE',
    riskSeverity: 'CRITICAL',
    description: 'Kế toán viên lập lệnh ủy nhiệm chi / chuyển khoản không được kiêm nhiệm vai trò Ký duyệt lệnh với ngân hàng (Bank Signer).',
    conflictingPermissions: ['BANK_TRANSFER_CREATE', 'BANK_SIGNER_EXECUTE'],
    status: 'PASSED',
    violationCount: 0,
    details: 'Quy trình Maker-Checker ngân hàng M32-M33 tuân thủ 100% chuẩn mực kiểm toán tài chính.',
    lastAudited: '2026-09-15 08:15:00',
    remediationGuide: 'Tách tài khoản Người lập lệnh và Người ký số duyệt chuyển tiền.',
  },
  {
    id: 'SOD_09_AUDITOR_INDEPENDENCE',
    code: 'SOD-AUDIT-09',
    name: 'Tính Độc Lập Tuyệt Đối Của Kiểm Toán Viên Nội Bộ',
    category: 'COMPLIANCE',
    riskSeverity: 'HIGH',
    description: 'Kiểm toán viên nội bộ (Auditor) chỉ có quyền Đọc (Read/View/Export) và không được cấp quyền Ghi hoặc Sửa chứng từ vận hành.',
    conflictingPermissions: ['AUDIT_LOG_READ', 'OPERATIONAL_VOUCHER_WRITE'],
    status: 'PASSED',
    violationCount: 0,
    details: 'Vai trò SYSTEM_AUDITOR được giới hạn Read-Only trên toàn bộ 42 phân hệ, bảo đảm tính khách quan.',
    lastAudited: '2026-09-15 08:20:00',
    remediationGuide: 'Chỉ cấp quyền VIEW và EXPORT cho nhóm tài khoản kiểm toán viên.',
  },
  {
    id: 'SOD_10_EXPORT_DATA_DLP',
    code: 'SOD-SEC-10',
    name: 'Kiểm Soát Xuất Dữ Liệu Chống Rò Rỉ Thông Tin Doanh Nghiệp (DLP)',
    category: 'DATA_LOSS_PREVENTION',
    riskSeverity: 'HIGH',
    description: 'Quyền EXPORT dữ liệu danh sách khách hàng, công nợ, giá thành phải tách biệt khỏi quyền VIEW thông thường.',
    conflictingPermissions: ['BULK_DATA_EXPORT_UNRESTRICTED', 'UNAUTHORIZED_EXFILTRATION'],
    status: 'PASSED',
    violationCount: 0,
    details: 'Chính sách DLP phân quyền EXPORT độc lập đã được kích hoạt trên toàn bộ 42 module.',
    lastAudited: '2026-09-15 08:25:00',
    remediationGuide: 'Bật kiểm soát EXPORT riêng biệt tại tab Ma Trận Quyền Hạt Nhân.',
  },
];

export const MODULES_42_CATALOG = [
  { id: 'M01', name: 'Trung Tâm Điều Hành (Workspace Hub)', category: 'Hệ thống', legacyCodes: ['hub:view', 'workspace:read'] },
  { id: 'M02', name: 'Tuân Thủ Kiểm Toán (Audit Compliance)', category: 'Hệ thống', legacyCodes: ['audit:read', 'compliance:verify'] },
  { id: 'M03', name: 'Thiết Lập Hệ Thống (System Settings)', category: 'Hệ thống', legacyCodes: ['settings:read', 'settings:write'] },
  { id: 'M04', name: 'SuperAdmin & Phân Quyền Hạt Nhân', category: 'Hệ thống', legacyCodes: ['admin:master', 'rbac:manage'] },
  { id: 'M05', name: 'Trục Kiến Trúc Sự Kiện (EventBus EDA)', category: 'Hệ thống', legacyCodes: ['eventbus:monitor', 'eventbus:emit'] },
  { id: 'M06', name: 'Nghiên Cứu & Phát Triển (R&D Lab)', category: 'Sản xuất', legacyCodes: ['rd:read', 'rd:write'] },
  { id: 'M07', name: 'Dữ Liệu Chủ Doanh Nghiệp (Master Data)', category: 'Hệ thống', legacyCodes: ['masterdata:read', 'masterdata:write'] },
  { id: 'M08', name: 'Đơn Đặt Hàng Mua (Purchase Orders)', category: 'Chuỗi cung ứng', legacyCodes: ['purchase:read', 'purchase:write', 'po:approve'] },
  { id: 'M09', name: 'Quản Trị Nhà Cung Cấp (Suppliers SRM)', category: 'Chuỗi cung ứng', legacyCodes: ['supplier:read', 'supplier:evaluate'] },
  { id: 'M10', name: 'Chiến Lược Nguồn Cung (Strategic Sourcing)', category: 'Chuỗi cung ứng', legacyCodes: ['sourcing:read', 'sourcing:bid'] },
  { id: 'M11', name: 'Đánh Giá Hiệu Năng NCC (SRM Portal)', category: 'Chuỗi cung ứng', legacyCodes: ['srm:portal', 'supplier:score'] },
  { id: 'M12', name: 'Quản Trị Cơ Hội & Phễu Bán (CRM Pipeline)', category: 'Kinh doanh', legacyCodes: ['crm:lead', 'crm:deal'] },
  { id: 'M13', name: 'Đơn Hàng Bán & Giao Nhận (Sales Orders)', category: 'Kinh doanh', legacyCodes: ['sales:order', 'sales:approve'] },
  { id: 'M14', name: 'Chính Sách Hoa Hồng (Sales Commission)', category: 'Kinh doanh', legacyCodes: ['commission:calc', 'commission:payout'] },
  { id: 'M15', name: 'Đổi Trả & Bảo Hành (Returns & RMA)', category: 'Kinh doanh', legacyCodes: ['rma:read', 'rma:approve'] },
  { id: 'M16', name: 'Điểm Bán Hàng & Thu Ngân (POS Retail)', category: 'Kinh doanh', legacyCodes: ['pos:sell', 'pos:close_shift'] },
  { id: 'M17', name: 'Quản Lý Kho Hạt Nhân (Core Inventory)', category: 'Kho vận', legacyCodes: ['inventory:read', 'inventory:write'] },
  { id: 'M18', name: 'Trung Tâm Kho Vận (WMS Hub)', category: 'Kho vận', legacyCodes: ['wms:inbound', 'wms:outbound'] },
  { id: 'M19', name: 'Kiểm Kê Tồn Kho (Stocktake & Audit)', category: 'Kho vận', legacyCodes: ['stocktake:count', 'stocktake:finalize'] },
  { id: 'M20', name: 'Điều Chỉnh Tồn Kho (Stock Adjustment)', category: 'Kho vận', legacyCodes: ['stock_adj:create', 'stock_adj:approve'] },
  { id: 'M21', name: 'Điều Chuyển Nội Bộ (Internal Transfers)', category: 'Kho vận', legacyCodes: ['transfer:request', 'transfer:ship', 'transfer:receive'] },
  { id: 'M22', name: 'Quản Lý Lô Sản Xuất (Lots & Batches)', category: 'Kho vận', legacyCodes: ['lot:trace', 'lot:hold'] },
  { id: 'M23', name: 'Định Danh Thiết Bị (Serials & IMEI)', category: 'Kho vận', legacyCodes: ['serial:assign', 'serial:lookup'] },
  { id: 'M24', name: 'WMS Nâng Cao & Tự Động Hóa', category: 'Kho vận', legacyCodes: ['wms_adv:zone', 'wms_adv:wave'] },
  { id: 'M25', name: 'Định Mức Sản Phẩm (Manufacturing BOM)', category: 'Sản xuất', legacyCodes: ['mfg:bom_view', 'mfg:bom_edit'] },
  { id: 'M26', name: 'Kế Hoạch Cung Ứng (SCM Planning)', category: 'Sản xuất', legacyCodes: ['scm:mrp', 'scm:mps'] },
  { id: 'M27', name: 'Quản Trị Tài Sản & Bảo Trì (EAM)', category: 'Bảo trì', legacyCodes: ['eam:asset', 'eam:workorder'] },
  { id: 'M28', name: 'Nhân Sự & Tiền Lương (HR & Payroll)', category: 'Nhân sự', legacyCodes: ['hr:employee', 'payroll:process'] },
  { id: 'M29', name: 'Quản Lý Tài Liệu Số (DMS Documents)', category: 'Hệ thống', legacyCodes: ['dms:read', 'dms:sign'] },
  { id: 'M30', name: 'Sổ Cái Tổng Hợp (Finance & GL)', category: 'Tài chính', legacyCodes: ['accounting:read', 'accounting:journal_post'] },
  { id: 'M31', name: 'Hóa Đơn Phải Thu / Phải Trả (AR/AP)', category: 'Tài chính', legacyCodes: ['invoice:issue', 'invoice:settle'] },
  { id: 'M32', name: 'Quản Trị Thu Chi & Quỹ (Treasury)', category: 'Tài chính', legacyCodes: ['treasury:voucher', 'cash:payout'] },
  { id: 'M33', name: 'Đối Soát Số Dư Ngân Hàng (Bank Recon)', category: 'Tài chính', legacyCodes: ['bank:statement', 'bank:reconcile'] },
  { id: 'M34', name: 'Báo Cáo Tài Chính Hợp Nhất', category: 'Tài chính', legacyCodes: ['fin_report:generate', 'fin_report:close'] },
  { id: 'M35', name: 'Quản Trị Dự Án & Tiến Độ (WBS)', category: 'Dự án', legacyCodes: ['project:wbs', 'project:budget'] },
  { id: 'M36', name: 'Quản Lý Vận Tải & Định Tuyến (TMS)', category: 'Kho vận', legacyCodes: ['tms:route', 'tms:dispatch'] },
  { id: 'M37', name: 'Phân Tích Thông Minh (BI Analytics)', category: 'Hệ thống', legacyCodes: ['bi:dashboard', 'bi:export'] },
  { id: 'M38', name: 'Hỗ Trợ & Khiếu Nại (Service Desk)', category: 'Vận hành', legacyCodes: ['helpdesk:ticket', 'sla:escalate'] },
  { id: 'M39', name: 'Kiểm Soát Chất Lượng (QMS Inspection)', category: 'Chất lượng', legacyCodes: ['qc:inspect', 'qc:approve_coa'] },
  { id: 'M40', name: 'An Toàn Sức Khỏe Môi Trường (EHS)', category: 'Chất lượng', legacyCodes: ['ehs:incident', 'ehs:audit'] },
  { id: 'M41', name: 'Quản Trị Giá & Chiết Khấu (Pricing)', category: 'Quản trị giá', legacyCodes: ['pricing:rule', 'pricing:override'] },
  { id: 'M42', name: 'Phân Bổ Chi Phí Đích (Landed Cost)', category: 'Quản trị giá', legacyCodes: ['costing:allocate', 'costing:post_gl'] },
  { id: 'M43', name: 'Hồ Sơ Ngành Hàng (Industry Profiles)', category: 'Dữ liệu chủ', legacyCodes: ['industry:read', 'industry:manage'] },
];

export const INITIAL_SESSIONS = [
  {
    id: 'sess_01',
    userId: 1,
    username: 'admin',
    fullName: 'Hoàng Nam (SuperAdmin)',
    roleCode: 'SUPER_ADMIN',
    ipAddress: '192.168.1.10',
    device: 'MacBook Pro M3 Max (Apple Silicon)',
    browser: 'Chrome 128 / macOS Sonoma',
    loginTime: '2026-09-15 08:30:15',
    lastActive: '2026-09-15 09:42:10',
    mfaVerified: true,
    tokenChecksum: 'sha256:7f9b8c1d3e5a2b4c6e8f0a1b2c3d4e5f',
    isCurrent: true,
  },
  {
    id: 'sess_02',
    userId: 2,
    username: 'cfo',
    fullName: 'Nguyễn Thị Hương (CFO)',
    roleCode: 'CFO_DIRECTOR',
    ipAddress: '192.168.1.25',
    device: 'Dell XPS 15 (Windows 11 Enterprise)',
    browser: 'Edge 128 / Windows 11',
    loginTime: '2026-09-15 08:45:00',
    lastActive: '2026-09-15 09:38:22',
    mfaVerified: true,
    tokenChecksum: 'sha256:3a1b5c7d9e1f3a5b7c9d1e3f5a7b9c1d',
    isCurrent: false,
  },
  {
    id: 'sess_03',
    userId: 3,
    username: 'warehouse',
    fullName: 'Trần Văn Kho (WMS Lead)',
    roleCode: 'WH_REGIONAL_DIRECTOR',
    ipAddress: '10.0.4.150',
    device: 'Zebra TC52 Industrial Android',
    browser: 'Chrome Mobile 126',
    loginTime: '2026-09-15 07:15:30',
    lastActive: '2026-09-15 09:40:05',
    mfaVerified: false,
    tokenChecksum: 'sha256:2b4d6f8a0c2e4a6c8e0a2c4e6a8c0e2a',
    isCurrent: false,
  },
  {
    id: 'sess_04',
    userId: 4,
    username: 'sales',
    fullName: 'Lê Thị Bán Hàng (O2C Lead)',
    roleCode: 'SALES_COMMERCE_OPERATOR',
    ipAddress: '113.161.44.82',
    device: 'iPad Pro 12.9 M2',
    browser: 'Safari 18 / iPadOS',
    loginTime: '2026-09-15 09:00:10',
    lastActive: '2026-09-15 09:35:48',
    mfaVerified: true,
    tokenChecksum: 'sha256:9c8b7a6f5e4d3c2b1a0f9e8d7c6b5a4f',
    isCurrent: false,
  },
];

export const INITIAL_AUDIT_LOGS = [
  {
    id: 'AUD-2026-09-001',
    actorUsername: 'admin',
    actorName: 'Hoàng Nam (SuperAdmin)',
    actionType: 'ROLE_PERM_UPDATE',
    targetType: 'ROLE',
    targetCode: 'WH_REGIONAL_DIRECTOR',
    oldValue: 'M19 (Stocktake): EXPORT=FALSE',
    newValue: 'M19 (Stocktake): EXPORT=TRUE',
    reason: 'Cấp quyền xuất báo cáo kiểm kê phục vụ kiểm toán tài chính quý III',
    ipAddress: '192.168.1.10',
    timestamp: '2026-09-15 08:45:12',
    sha256Checksum: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
  },
  {
    id: 'AUD-2026-09-002',
    actorUsername: 'admin',
    actorName: 'Hoàng Nam (SuperAdmin)',
    actionType: 'USER_STATUS_CHANGE',
    targetType: 'USER',
    targetCode: 'operator',
    oldValue: 'STATUS: ACTIVE',
    newValue: 'STATUS: LOCKED',
    reason: 'Khóa tài khoản tạm thời theo đề xuất của Quản đốc Phân xưởng',
    ipAddress: '192.168.1.10',
    timestamp: '2026-09-14 16:30:00',
    sha256Checksum: '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8',
  },
  {
    id: 'AUD-2026-09-003',
    actorUsername: 'admin',
    actorName: 'Hoàng Nam (SuperAdmin)',
    actionType: 'RLS_POLICY_ENFORCE',
    targetType: 'SYSTEM',
    targetCode: 'BRANCH_RLS',
    oldValue: 'STRICT_MODE: FALSE',
    newValue: 'STRICT_MODE: TRUE',
    reason: 'Kích hoạt chính sách cô lập dữ liệu tuyệt đối giữa các chi nhánh',
    ipAddress: '192.168.1.10',
    timestamp: '2026-09-14 14:10:25',
    sha256Checksum: '4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a',
  },
  {
    id: 'AUD-2026-09-004',
    actorUsername: 'admin',
    actorName: 'Hoàng Nam (SuperAdmin)',
    actionType: 'DELEGATION_GRANT',
    targetType: 'USER',
    targetCode: 'cfo -> accountant_lead',
    oldValue: 'NONE',
    newValue: 'MODULES: M30, M31, M32 (10/09 - 20/09/2026)',
    reason: 'Ủy quyền phê duyệt chứng từ kế toán trong thời gian công tác',
    ipAddress: '192.168.1.10',
    timestamp: '2026-09-10 09:00:00',
    sha256Checksum: 'ef2d127de37b942baad06145e54b0c619a1f22327b2ebbcfbec78f5564afe39d',
  },
];

export const INITIAL_DELEGATIONS = [
  {
    id: 'del_01',
    delegatorUsername: 'cfo',
    delegatorName: 'Nguyễn Thị Hương (CFO)',
    delegateeUsername: 'accountant_lead',
    delegateeName: 'Trần Mai Anh (Kế Toán Trưởng)',
    moduleScopes: ['M30', 'M31', 'M32'],
    branchScope: 'HQ',
    startDate: '2026-09-10',
    endDate: '2026-09-20',
    reason: 'Công tác khảo sát vận hành chi nhánh miền Trung',
    status: 'ACTIVE' as const,
  },
  {
    id: 'del_02',
    delegatorUsername: 'warehouse',
    delegatorName: 'Trần Văn Kho (WMS Lead)',
    delegateeUsername: 'wh_deputy',
    delegateeName: 'Vũ Đình Nam (Phó Kho Trưởng)',
    moduleScopes: ['M17', 'M19', 'M20'],
    branchScope: 'BR_HO',
    startDate: '2026-09-01',
    endDate: '2026-09-07',
    reason: 'Nghỉ phép thường niên',
    status: 'EXPIRED' as const,
  },
];

export const INITIAL_PASSWORD_POLICY = {
  minLength: 12,
  requireUppercase: true,
  requireNumber: true,
  requireSpecialChar: true,
  expiryDays: 90,
  forceFirstChange: true,
  mfaEnforcedRoles: ['SUPER_ADMIN', 'ADMIN', 'CFO_DIRECTOR'],
};

export const INITIAL_TENANT_BRANCHES = [
  {
    id: 1,
    code: 'HQ',
    name: 'Trụ Sở Chính Tập Đoàn (Hà Nội)',
    glCode: 'GL-1000-HQ',
    defaultWarehouse: 'KHO_TONG_BAC_NINH',
    manager: 'Hoàng Nam (SuperAdmin)',
    creditLimit: 50000000000,
    createdAt: '2026-01-01',
  },
  {
    id: 2,
    code: 'BR_HCM',
    name: 'Tổng Chi Nhánh Miền Nam (TP.HCM)',
    glCode: 'GL-2000-HCM',
    defaultWarehouse: 'KHO_TRUNG_CHUYEN_BINH_DUONG',
    manager: 'Nguyễn Văn Nam (Giám Đốc Chi Nhánh)',
    creditLimit: 30000000000,
    createdAt: '2026-01-15',
  },
  {
    id: 3,
    code: 'BR_DN',
    name: 'Chi Nhánh Miền Trung (Đà Nẵng)',
    glCode: 'GL-3000-DN',
    defaultWarehouse: 'KHO_HOA_CAM_DA_NANG',
    manager: 'Lê Thanh Tùng',
    creditLimit: 15000000000,
    createdAt: '2026-02-01',
  },
  {
    id: 4,
    code: 'BR_CT',
    name: 'Chi Nhánh Tây Nam Bộ (Cần Thơ)',
    glCode: 'GL-4000-CT',
    defaultWarehouse: 'KHO_TRA_NOC_CAN_THO',
    manager: 'Đặng Quốc Bảo',
    creditLimit: 10000000000,
    createdAt: '2026-03-01',
  },
];
