import { ConsolidationEntity, IntercompanyElimination, FxRule, GroupStructureNode, CoaMappingRule, IntercompanyMatchItem, ConsolidationAdjustmentJournal, PeriodCloseStage, ConsolidationReport, TransferPricingData, DualReportingBridgeData, M34Props } from "./types";

export const INITIAL_ENTITIES: ConsolidationEntity[] = [
      {
        id: 1,
        code: "BR_HO",
        name: "Tập đoàn NexusSync Corporation (Trụ sở chính)",
        ownershipPercent: 100,
        votingRightsPercent: 100,
        currency: "VND",
        entityType: "PARENT",
        consolidationMethod: "FULL_CONSOLIDATION",
        effectiveDate: "2020-01-01",
        revenue: 25400000000,
        expense: 18200000000,
        netIncome: 7200000000,
        assets: 65000000000,
        liabilities: 25000000000,
        equity: 40000000000,
        intercompanyAR: 1250000000,
        intercompanyAP: 400000000,
        status: "ACTIVE",
      },
      {
        id: 2,
        code: "BR_HCM",
        name: "Chi Nhánh TP. Hồ Chí Minh (Công ty con 100%)",
        ownershipPercent: 100,
        votingRightsPercent: 100,
        currency: "VND",
        entityType: "SUBSIDIARY",
        consolidationMethod: "FULL_CONSOLIDATION",
        effectiveDate: "2021-03-15",
        revenue: 18900000000,
        expense: 14100000000,
        netIncome: 4800000000,
        assets: 28000000000,
        liabilities: 11000000000,
        equity: 17000000000,
        intercompanyAR: 400000000,
        intercompanyAP: 1250000000,
        status: "ACTIVE",
      },
      {
        id: 3,
        code: "BR_DN",
        name: "Chi Nhánh Đà Nẵng (Công ty con 80%)",
        ownershipPercent: 80,
        votingRightsPercent: 80,
        currency: "VND",
        entityType: "SUBSIDIARY",
        consolidationMethod: "FULL_CONSOLIDATION",
        effectiveDate: "2022-06-01",
        revenue: 9600000000,
        expense: 7200000000,
        netIncome: 2400000000,
        assets: 14000000000,
        liabilities: 5500000000,
        equity: 8500000000,
        intercompanyAR: 150000000,
        intercompanyAP: 150000000,
        status: "ACTIVE",
      },
      {
        id: 4,
        code: "BR_SG_GLOBAL",
        name: "NexusSync Global Pte Ltd (Singapore Sub 100%)",
        ownershipPercent: 100,
        votingRightsPercent: 100,
        currency: "USD",
        entityType: "SUBSIDIARY",
        consolidationMethod: "FULL_CONSOLIDATION",
        effectiveDate: "2023-01-10",
        revenue: 30480000000, // $1.2M translated at 25,400
        expense: 22860000000,
        netIncome: 7620000000,
        assets: 41000000000,
        liabilities: 15000000000,
        equity: 26000000000,
        intercompanyAR: 0,
        intercompanyAP: 0,
        status: "ACTIVE",
      },
    ];
export const INITIAL_ELIMINATIONS: IntercompanyElimination[] = [
      {
        id: 1,
        eliminationCode: "ELIM-2026-001",
        type: "IC_SALES_PURCHASE",
        sourceBranch: "BR_HO",
        targetBranch: "BR_HCM",
        accountCode: "5111 / 6321",
        description: "Loại trừ doanh thu & giá vốn nội bộ bán phần mềm SaaS",
        amount: 1250000000,
        status: "POSTED",
        date: "2026-02-15",
      },
      {
        id: 2,
        eliminationCode: "ELIM-2026-002",
        type: "IC_AR_AP",
        sourceBranch: "BR_HO",
        targetBranch: "BR_HCM",
        accountCode: "1311 / 3311",
        description: "Loại trừ công nợ phải thu & phải trả nội bộ cuối kỳ",
        amount: 1250000000,
        status: "POSTED",
        date: "2026-02-28",
      },
      {
        id: 3,
        eliminationCode: "ELIM-2026-003",
        type: "IC_SERVICE_FEE",
        sourceBranch: "BR_HO",
        targetBranch: "BR_DN",
        accountCode: "5113 / 6422",
        description: "Loại trừ phí quản trị tập đoàn & hỗ trợ IT cho chi nhánh Đà Nẵng",
        amount: 400000000,
        status: "POSTED",
        date: "2026-02-25",
      },
    ];
export const INITIAL_COA_MAPPINGS: CoaMappingRule[] = [
      {
        id: "MAP-001",
        entityCode: "BR_SG_GLOBAL",
        localAccountCode: "4000-REV-SG",
        localAccountName: "SaaS Sales Revenue Singapore",
        groupAccountCode: "5111-GROUP",
        groupAccountName: "Doanh thu bán hàng & dịch vụ hợp nhất",
        translationCategory: "PNL",
        mappingType: "DIRECT",
        status: "MAPPED",
      },
      {
        id: "MAP-002",
        entityCode: "BR_SG_GLOBAL",
        localAccountCode: "5000-COS-SG",
        localAccountName: "Cost of Cloud Services",
        groupAccountCode: "6321-GROUP",
        groupAccountName: "Giá vốn hàng bán hợp nhất",
        translationCategory: "PNL",
        mappingType: "DIRECT",
        status: "MAPPED",
      },
      {
        id: "MAP-003",
        entityCode: "BR_DN",
        localAccountCode: "511-DN",
        localAccountName: "Doanh thu dịch vụ CNTT Miền Trung",
        groupAccountCode: "5111-GROUP",
        groupAccountName: "Doanh thu bán hàng & dịch vụ hợp nhất",
        translationCategory: "PNL",
        mappingType: "DIRECT",
        status: "MAPPED",
      },
      {
        id: "MAP-004",
        entityCode: "BR_SG_GLOBAL",
        localAccountCode: "1100-CASH-USD",
        localAccountName: "Bank Account DBS Singapore (USD)",
        groupAccountCode: "1112-GROUP",
        groupAccountName: "Tiền gửi ngân hàng ngoại tệ",
        translationCategory: "BALANCE_SHEET",
        mappingType: "DIRECT",
        status: "MAPPED",
      },
      {
        id: "MAP-005",
        entityCode: "BR_HCM",
        localAccountCode: "131-HCM-IC",
        localAccountName: "Phải thu khách hàng nội bộ HO",
        groupAccountCode: "1361-GROUP",
        groupAccountName: "Phải thu nội bộ tập đoàn",
        translationCategory: "BALANCE_SHEET",
        mappingType: "RULE_BASED",
        status: "PENDING_REVIEW",
      },
    ];
export const INITIAL_IC_MATCHES: IntercompanyMatchItem[] = [
      {
        id: "ICM-101",
        entityA: "BR_HO",
        entityB: "BR_HCM",
        transactionType: "AR_AP",
        period: "2026-Q1",
        amountA: 1250000000,
        currencyA: "VND",
        amountB: 1250000000,
        currencyB: "VND",
        differenceVND: 0,
        status: "MATCHED",
        docRefA: "INV-HO-2026-088",
        docRefB: "BILL-HCM-2026-042",
        accountA: "1311",
        accountB: "3311",
        notes: "Khớp hoàn toàn 100% công nợ bán hàng SaaS nội bộ",
      },
      {
        id: "ICM-102",
        entityA: "BR_HO",
        entityB: "BR_DN",
        transactionType: "REVENUE_EXPENSE",
        period: "2026-Q1",
        amountA: 400000000,
        currencyA: "VND",
        amountB: 395000000,
        currencyB: "VND",
        differenceVND: 5000000,
        status: "PARTIALLY_MATCHED",
        docRefA: "INV-HO-2026-092",
        docRefB: "BILL-DN-2026-018",
        accountA: "5113",
        accountB: "6422",
        notes: "Lệch 5 Triệu VNĐ do phí chiết khấu thanh toán chưa ghi nhận tại BR_DN",
      },
      {
        id: "ICM-103",
        entityA: "BR_HO",
        entityB: "BR_SG_GLOBAL",
        transactionType: "LOAN",
        period: "2026-Q1",
        amountA: 1270000000, // $50,000 at 25,400
        currencyA: "VND",
        amountB: 1270000000,
        currencyB: "USD",
        differenceVND: 0,
        status: "MATCHED",
        docRefA: "LOAN-AGR-SG-01",
        docRefB: "LOAN-REC-SG-01",
        accountA: "1288",
        accountB: "3411",
        notes: "Vay ngắn hạn nội bộ Singapore Sub $50,000 USD",
      },
      {
        id: "ICM-104",
        entityA: "BR_HCM",
        entityB: "BR_DN",
        transactionType: "REVENUE_EXPENSE",
        period: "2026-Q1",
        amountA: 85000000,
        currencyA: "VND",
        amountB: 0,
        currencyB: "VND",
        differenceVND: 85000000,
        status: "EXCEPTION",
        docRefA: "INV-HCM-2026-105",
        docRefB: "CHƯA_GHI_NHẬN",
        accountA: "5111",
        accountB: "6321",
        notes: "Hóa đơn chuyển kho linh kiện HCM gửi Đà Nẵng đang trên đường chưa nhập kho",
      },
    ];
export const INITIAL_ADJUSTMENT_JOURNALS: ConsolidationAdjustmentJournal[] = [
      {
        id: "CAJ-2026-01",
        journalNo: "CONSO-ADJ-001",
        period: "2026-Q1",
        type: "OWNERSHIP_NCI",
        reason: "Ghi nhận cổ đông không kiểm soát (NCI 20%) tại Chi nhánh Đà Nẵng",
        entity: "BR_DN",
        drAccount: "4211 (Lợi nhuận giữ lại)",
        crAccount: "4190 (Lợi ích Cổ đông NCI)",
        amountVND: 480000000, // 20% of 2.4B
        createdBy: "Hoàng Nam (CFO)",
        approvedBy: "Trần Đức (Audit Lead)",
        status: "POSTED",
        auditTrail: "SHA256: 9f8a...c4b2 (Consolidation Engine Auto-Calculated)",
        createdAt: "2026-02-28 16:30",
      },
      {
        id: "CAJ-2026-02",
        journalNo: "CONSO-ADJ-002",
        period: "2026-Q1",
        type: "FX_TRANSLATION",
        reason: "Ghi nhận chênh lệch tỷ giá quy đổi tài sản ròng Singapore Sub vào Quỹ CTA Equity",
        entity: "BR_SG_GLOBAL",
        drAccount: "4131 (Chênh lệch tỷ giá BCTC)",
        crAccount: "4180 (Quỹ Chuyển đổi CTA)",
        amountVND: 350000000,
        createdBy: "Nguyễn Hương (Senior Accountant)",
        approvedBy: "Hoàng Nam (CFO)",
        status: "APPROVED",
        auditTrail: "SHA256: 4e7d...e19f",
        createdAt: "2026-02-28 17:15",
      },
    ];
export const INITIAL_PERIOD_CLOSE_STAGES: PeriodCloseStage[] = [
      { id: "S1", stageCode: "OPEN", name: "1. Mở Kỳ Hợp Nhất", description: "Khởi tạo kỳ hợp nhất báo cáo tài chính mới", status: "COMPLETED", completedBy: "System", completedAt: "2026-01-01" },
      { id: "S2", stageCode: "DATA_COLLECTION", name: "2. Thu Thập Dữ Liệu GL", description: "Trích xuất Trial Balance & BCTC từ 4 công ty thành viên", status: "COMPLETED", completedBy: "ERP Auto-Sync", completedAt: "2026-02-27" },
      { id: "S3", stageCode: "VALIDATION", name: "3. Kiểm Tra Data Validation", description: "Xác thực COA Mapping & cân đối bảng tính sổ cái", status: "COMPLETED", completedBy: "Hoàng Nam (Admin)", completedAt: "2026-02-27" },
      { id: "S4", stageCode: "INTERCOMPANY_MATCHING", name: "4. Đối Soát Giao Dịch Nội Bộ", description: "Khớp nối AR/AP và Revenue/Expense giữa các đơn vị", status: "IN_PROGRESS", completedBy: "Pending CFO Sign-off" },
      { id: "S5", stageCode: "ELIMINATION", name: "5. Bút Toán Loại Trừ Nội Bộ", description: "Tạo bút toán loại trừ Doanh thu, Công nợ & Đầu tư", status: "PENDING" },
      { id: "S6", stageCode: "ADJUSTMENT", name: "6. Bút Toán Điều Chỉnh Hợp Nhất", description: "Ghi nhận NCI, URP Tồn kho & Phân bổ Lợi thế thương mại", status: "PENDING" },
      { id: "S7", stageCode: "CONSOLIDATION", name: "7. Chạy Động Cơ Hợp Nhất", description: "Tổng hợp BCTC Hợp Nhất Tập Đoàn (Form B 01/02-DN/HN)", status: "PENDING" },
      { id: "S8", stageCode: "REVIEW", name: "8. Rà Soát & Kiểm Toán CFO", description: "CFO & Kiểm toán viên độc lập thẩm định số liệu", status: "PENDING" },
      { id: "S9", stageCode: "APPROVED", name: "9. Phê Duyệt Hội Đồng Quản Trị", description: "Phê duyệt chính thức phát hành BCTC Hợp Nhất", status: "PENDING" },
      { id: "S10", stageCode: "CLOSED", name: "10. Khóa Kỳ Hợp Nhất Immutable", description: "Khóa sổ bất biến, bảo vệ toàn vẹn Audit Trail", status: "LOCKED" },
    ];
export const INITIAL_TRANSFER_PRICING: TransferPricingData = {
      decree132ComplianceStatus: "VERIFIED_COMPLIANT (Đạt Ngưỡng Giao Dịch Độc Lập Arm's Length)",
      financialYear: "2026",
      groupGlobalThresholdEUR: 750000000,
      groupGlobalRevenueEUR: 3200000,
      globeEffectiveTaxRates: [
        {
          jurisdiction: "Việt Nam (VN)",
          statutoryTaxRate: 20,
          adjustedGlobeIncome: 22020000000,
          coveredTaxes: 4404000000,
          effectiveTaxRate: 20,
          topUpTaxRate: 0,
          topUpTaxAmountVND: 0,
          status: "COMPLIANT_ABOVE_15",
        },
        {
          jurisdiction: "Singapore (SG)",
          statutoryTaxRate: 17,
          concessionaryTaxRate: 10,
          adjustedGlobeIncome: 7620000000,
          coveredTaxes: 762000000,
          effectiveTaxRate: 10,
          topUpTaxRate: 5,
          topUpTaxAmountVND: 381000000,
          status: "SAFE_HARBOUR_DE_MINIMIS",
        },
      ],
      interestCapRule30Ebitda: {
        ebitdaVND: 28500000000,
        netInterestExpenseVND: 6200000000,
        cap30EbitdaVND: 8550000000,
        deductibleInterestVND: 6200000000,
        nondeductibleCarriedForwardVND: 0,
        isCompliant: true,
      },
      relatedPartyTransactions: [
        {
          id: "RPT-2026-01",
          transactionType: "Bán hàng dịch vụ phần mềm SaaS",
          sourceEntity: "BR_HO",
          targetEntity: "BR_HCM",
          valueVND: 1250000000,
          tpMethod: "TNMM (So sánh Biên Lợi nhuận Ròng)",
          benchmarkArmLengthRange: "8.5% - 12.0%",
          actualMargin: "10.2%",
          isArmLength: true,
        },
        {
          id: "RPT-2026-02",
          transactionType: "Phí quản trị tập đoàn & hỗ trợ IT",
          sourceEntity: "BR_HO",
          targetEntity: "BR_DN",
          valueVND: 400000000,
          tpMethod: "CUP (So sánh Giá tự do)",
          benchmarkArmLengthRange: "Khớp giá thị trường độc lập",
          actualMargin: "Khớp 100%",
          isArmLength: true,
        },
        {
          id: "RPT-2026-03",
          transactionType: "Khoản vay ngắn hạn nội bộ Singapore Sub",
          sourceEntity: "BR_HO",
          targetEntity: "BR_SG_GLOBAL",
          valueVND: 1270000000,
          tpMethod: "Interest Rate Benchmarking",
          benchmarkArmLengthRange: "4.5% - 6.0% / năm",
          actualMargin: "5.2% / năm",
          isArmLength: true,
        },
      ],
      documentationFiles: [
        {
          fileType: "MASTER_FILE",
          title: "Hồ Sơ Tải Tập Đoàn (Master File - Nghị Định 132)",
          status: "GENERATED",
          lastUpdated: "2026-08-28",
          fileSize: "4.2 MB",
          summary: "Mô tả toàn bộ cấu trúc sở hữu toàn cầu, chuỗi giá trị logistics, quyền sở hữu trí tuệ ERP và chính sách giá chuyển nhượng tập đoàn NexusSync.",
        },
        {
          fileType: "LOCAL_FILE",
          title: "Hồ Sơ Quốc Gia (Local File - Nghị Định 132)",
          status: "GENERATED",
          lastUpdated: "2026-08-28",
          fileSize: "8.5 MB",
          summary: "Phân tích so sánh biên lợi nhuận độc lập, dữ liệu benchmarking cơ sở dữ liệu Orbis/Bureau van Dijk cho thị trường Việt Nam.",
        },
        {
          fileType: "CBCR",
          title: "Báo Cáo Lợi Nhuận Liên Quốc Gia (CbCR - Form Form 04/TĐ)",
          status: "FILED",
          lastUpdated: "2026-08-28",
          fileSize: "2.1 MB",
          summary: "Phân bổ lợi nhuận, doanh thu, thuế TNDN đã nộp và số lượng lao động theo từng quốc gia nhập OECD.",
        },
      ],
    };
